"""Unit tests for ImageGenerationService protocol and mock implementation."""

from pathlib import Path
from PIL import Image
import io

from bulkimagecreator.service import ImageGenerationService, MockImageGenerationService


def test_mock_service_protocol_conformance() -> None:
    mock_service = MockImageGenerationService()
    assert isinstance(mock_service, ImageGenerationService)


def test_mock_service_generates_valid_image(tmp_path: Path) -> None:
    service = MockImageGenerationService()
    ref_img = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref_img, format="PNG")

    result_bytes = service.generate_image(
        prompt="A serene landscape",
        reference_images=[ref_img],
        aspect_ratio="1:1",
        model="gemini-test",
    )

    assert isinstance(result_bytes, bytes)
    assert len(result_bytes) > 0

    # Verify generated bytes form a valid image readable by Pillow
    loaded_img = Image.open(io.BytesIO(result_bytes))
    assert loaded_img.size == (128, 128)
    assert len(service.call_history) == 1
    assert service.call_history[0]["prompt"] == "A serene landscape"
    assert service.call_history[0]["reference_images"] == [ref_img]
