"""Unit tests for ImageGenerationService protocol and mock implementation."""

from pathlib import Path
from PIL import Image
import io

from bulkimagecreator.service import ImageGenerationService, MockImageGenerationService


def test_mock_service_protocol_conformance() -> None:
    mock_service = MockImageGenerationService()
    assert isinstance(mock_service, ImageGenerationService)


def test_mock_service_generates_valid_image(tmp_path: Path) -> None:
    service = MockImageGenerationService()
    ref_img = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref_img, format="PNG")

    result_bytes = service.generate_image(
        prompt="A serene landscape",
        reference_images=[ref_img],
        aspect_ratio="1:1",
        model="gemini-test",
    )

    assert isinstance(result_bytes, bytes)
    assert len(result_bytes) > 0

    # Verify generated bytes form a valid image readable by Pillow
    loaded_img = Image.open(io.BytesIO(result_bytes))
    assert loaded_img.size == (128, 128)
    assert len(service.call_history) == 1
    assert service.call_history[0]["prompt"] == "A serene landscape"
    assert service.call_history[0]["reference_images"] == [ref_img]


def test_mock_service_generate_candidate_image(tmp_path: Path) -> None:
    service = MockImageGenerationService()
    ref1 = tmp_path / "ref1.png"
    ref2 = tmp_path / "ref2.png"
    Image.new("RGB", (32, 32), color="blue").save(ref1, format="PNG")
    Image.new("RGB", (32, 32), color="green").save(ref2, format="PNG")

    candidate_bytes = service.generate_candidate_image(
        source_images=[ref1, ref2],
        prompt="A fantasy castle",
        aspect_ratio="16:9",
    )

    assert isinstance(candidate_bytes, bytes)
    img = Image.open(io.BytesIO(candidate_bytes))
    assert img.format == "PNG"
    assert len(service.call_history) == 1
    assert service.call_history[0]["prompt"] == "A fantasy castle"
    assert service.call_history[0]["reference_images"] == [ref1, ref2]
    assert service.call_history[0]["aspect_ratio"] == "16:9"


def test_gemini_service_protocol_conformance() -> None:
    from unittest.mock import MagicMock
    from bulkimagecreator.service import GeminiImageGenerationService

    mock_client = MagicMock()
    gemini_service = GeminiImageGenerationService(client=mock_client)
    assert isinstance(gemini_service, ImageGenerationService)


def test_gemini_service_generate_candidate_image(tmp_path: Path) -> None:
    from unittest.mock import MagicMock
    from bulkimagecreator.service import GeminiImageGenerationService

    ref = tmp_path / "src.png"
    Image.new("RGB", (32, 32), color="white").save(ref, format="PNG")

    # Mock Gemini response
    dummy_png = io.BytesIO()
    Image.new("RGB", (64, 64), color="yellow").save(dummy_png, format="PNG")
    dummy_bytes = dummy_png.getvalue()

    mock_part = MagicMock()
    mock_part.inline_data.data = dummy_bytes
    mock_candidate = MagicMock()
    mock_candidate.content.parts = [mock_part]
    mock_response = MagicMock()
    mock_response.candidates = [mock_candidate]

    mock_client = MagicMock()
    mock_client.models.generate_content.return_value = mock_response

    service = GeminiImageGenerationService(client=mock_client)
    result = service.generate_candidate_image(
        source_images=[ref],
        prompt="A sunny day",
        aspect_ratio="4:3",
    )

    assert result == dummy_bytes
    mock_client.models.generate_content.assert_called_once()
    call_kwargs = mock_client.models.generate_content.call_args.kwargs
    assert call_kwargs["model"] == "gemini-2.5-flash-image"
    assert call_kwargs["config"].image_config.aspect_ratio == "4:3"


def test_mock_service_generate_variation_image(tmp_path: Path) -> None:
    service = MockImageGenerationService()
    seed_img = tmp_path / "00_seed.png"
    Image.new("RGB", (32, 32), color="purple").save(seed_img, format="PNG")

    var_bytes = service.generate_variation_image(
        seed_image=seed_img,
        prompt="A variation in oil paint style",
        aspect_ratio="1:1",
    )

    assert isinstance(var_bytes, bytes)
    img = Image.open(io.BytesIO(var_bytes))
    assert img.format == "PNG"
    assert len(service.call_history) == 1
    assert service.call_history[0]["prompt"] == "A variation in oil paint style"
    # ADR 0001: Exclusively seed image passed as reference
    assert service.call_history[0]["reference_images"] == [seed_img]
    assert service.call_history[0]["aspect_ratio"] == "1:1"


def test_gemini_service_generate_variation_image(tmp_path: Path) -> None:
    from unittest.mock import MagicMock
    from bulkimagecreator.service import GeminiImageGenerationService

    seed_img = tmp_path / "00_seed.png"
    Image.new("RGB", (32, 32), color="cyan").save(seed_img, format="PNG")

    dummy_png = io.BytesIO()
    Image.new("RGB", (64, 64), color="magenta").save(dummy_png, format="PNG")
    dummy_bytes = dummy_png.getvalue()

    mock_part = MagicMock()
    mock_part.inline_data.data = dummy_bytes
    mock_candidate = MagicMock()
    mock_candidate.content.parts = [mock_part]
    mock_response = MagicMock()
    mock_response.candidates = [mock_candidate]

    mock_client = MagicMock()
    mock_client.models.generate_content.return_value = mock_response

    service = GeminiImageGenerationService(client=mock_client)
    result = service.generate_variation_image(
        seed_image=seed_img,
        prompt="Cyberpunk neon style",
        aspect_ratio="9:16",
    )

    assert result == dummy_bytes
    mock_client.models.generate_content.assert_called_once()
    call_kwargs = mock_client.models.generate_content.call_args.kwargs
    assert call_kwargs["model"] == "gemini-2.5-flash-image"
    assert call_kwargs["config"].image_config.aspect_ratio == "9:16"
    # Multimodal contents: only 1 image (seed) + 1 prompt string
    contents = call_kwargs["contents"]
    assert len(contents) == 2
    assert contents[1] == "Cyberpunk neon style"


def test_gemini_service_disables_automatic_function_calling_and_emits_no_warning(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Assert GeminiImageGenerationService disables AFC so google-genai emits no deprecation warning."""
    import logging
    from google import genai
    from google.genai.models import Models
    from unittest.mock import MagicMock, patch
    from bulkimagecreator.service import GeminiImageGenerationService

    # Reset SDK warning latch to ensure warning would trigger if not properly disabled
    Models._logged_afc_warning = False

    test_img = tmp_path / "input.png"
    Image.new("RGB", (16, 16), color="red").save(test_img, format="PNG")

    dummy_png = io.BytesIO()
    Image.new("RGB", (32, 32), color="green").save(dummy_png, format="PNG")
    dummy_bytes = dummy_png.getvalue()

    mock_part = MagicMock()
    mock_part.inline_data.data = dummy_bytes
    mock_part.inline_data.mime_type = "image/png"
    mock_candidate = MagicMock()
    mock_candidate.content.parts = [mock_part]
    mock_response = MagicMock()
    mock_response.candidates = [mock_candidate]
    mock_response.prompt_feedback = None

    # Use a real genai.Client so models.generate_content validation & warning logic executes
    client = genai.Client(api_key="test-api-key")

    with patch.object(client.models, "_generate_content", return_value=mock_response):
        with caplog.at_level(logging.WARNING, logger="google_genai.models"):
            service = GeminiImageGenerationService(client=client)
            result = service.generate_image(
                prompt="Futuristic city",
                reference_images=[test_img],
                aspect_ratio="1:1",
            )

    assert result == dummy_bytes

    # Assert that no AFC warning was logged
    afc_warnings = [
        rec.message
        for rec in caplog.records
        if "Direct use of automatic function calling" in rec.message
    ]
    assert not afc_warnings, f"Unexpected AFC warning emitted: {afc_warnings}"


def test_gemini_service_forces_gemini_api_when_vertexai_env_var_set(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Assert GeminiImageGenerationService defaults to Gemini Developer API even if GOOGLE_GENAI_USE_VERTEXAI is set."""
    from bulkimagecreator.service import GeminiImageGenerationService

    monkeypatch.setenv("GOOGLE_GENAI_USE_VERTEXAI", "true")
    monkeypatch.setenv("GOOGLE_GENAI_USE_ENTERPRISE", "true")

    service = GeminiImageGenerationService(api_key="test-api-key")
    client = service._client

    assert client._api_client.vertexai is False
    assert "generativelanguage.googleapis.com" in client._api_client._http_options.base_url




def test_mock_service_transient_failure_retries_and_recovers(tmp_path: Path) -> None:
    from bulkimagecreator.exceptions import TransientGenerationError

    service = MockImageGenerationService()
    service.set_transient_failure_for_prompt("Retryable prompt", retries_before_success=2)
    ref = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref, format="PNG")

    # Call 1: raises TransientGenerationError
    import pytest

    with pytest.raises(TransientGenerationError, match="HTTP 429"):
        service.generate_image(prompt="Retryable prompt", reference_images=[ref])

    # Call 2: raises TransientGenerationError
    with pytest.raises(TransientGenerationError, match="HTTP 429"):
        service.generate_image(prompt="Retryable prompt", reference_images=[ref])

    # Call 3: succeeds
    img_bytes = service.generate_image(prompt="Retryable prompt", reference_images=[ref])
    assert isinstance(img_bytes, bytes)
    assert len(img_bytes) > 0


def test_mock_service_safety_block(tmp_path: Path) -> None:
    import pytest
    from bulkimagecreator.exceptions import SafetyBlockError

    service = MockImageGenerationService()
    service.set_safety_block_for_prompt("Toxic prompt", error_message="Safety violation")
    ref = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref, format="PNG")

    with pytest.raises(SafetyBlockError, match="Safety violation"):
        service.generate_image(prompt="Toxic prompt", reference_images=[ref])


def test_mock_service_non_transient_failure(tmp_path: Path) -> None:
    import pytest
    from bulkimagecreator.exceptions import NonTransientGenerationError

    service = MockImageGenerationService()
    service.set_non_transient_failure_for_prompt("Bad prompt", error_message="Invalid argument")
    ref = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref, format="PNG")

    with pytest.raises(NonTransientGenerationError, match="Invalid argument"):
        service.generate_image(prompt="Bad prompt", reference_images=[ref])


def test_gemini_service_maps_429_api_error_to_transient(tmp_path: Path) -> None:
    from unittest.mock import MagicMock
    import pytest
    from google.genai.errors import ClientError
    from bulkimagecreator.exceptions import TransientGenerationError
    from bulkimagecreator.service import GeminiImageGenerationService

    mock_client = MagicMock()
    err_json = {"error": {"code": 429, "message": "Resource exhausted", "status": "RESOURCE_EXHAUSTED"}}
    mock_client.models.generate_content.side_effect = ClientError(429, err_json)

    service = GeminiImageGenerationService(client=mock_client)
    ref = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref, format="PNG")

    with pytest.raises(TransientGenerationError, match="Transient Gemini API failure"):
        service.generate_image(prompt="Prompt", reference_images=[ref])


def test_gemini_service_maps_503_api_error_to_transient(tmp_path: Path) -> None:
    from unittest.mock import MagicMock
    import pytest
    from google.genai.errors import ServerError
    from bulkimagecreator.exceptions import TransientGenerationError
    from bulkimagecreator.service import GeminiImageGenerationService

    mock_client = MagicMock()
    err_json = {"error": {"code": 503, "message": "Service unavailable", "status": "UNAVAILABLE"}}
    mock_client.models.generate_content.side_effect = ServerError(503, err_json)

    service = GeminiImageGenerationService(client=mock_client)
    ref = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref, format="PNG")

    with pytest.raises(TransientGenerationError, match="Transient Gemini API failure"):
        service.generate_image(prompt="Prompt", reference_images=[ref])


def test_gemini_service_maps_timeout_to_transient(tmp_path: Path) -> None:
    from unittest.mock import MagicMock
    import pytest
    from bulkimagecreator.exceptions import TransientGenerationError
    from bulkimagecreator.service import GeminiImageGenerationService

    mock_client = MagicMock()
    mock_client.models.generate_content.side_effect = TimeoutError("Request timed out")

    service = GeminiImageGenerationService(client=mock_client)
    ref = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref, format="PNG")

    with pytest.raises(TransientGenerationError, match="Transient Gemini API failure"):
        service.generate_image(prompt="Prompt", reference_images=[ref])


def test_gemini_service_maps_safety_finish_reason_to_safety_block_error(tmp_path: Path) -> None:
    from unittest.mock import MagicMock
    import pytest
    from bulkimagecreator.exceptions import SafetyBlockError
    from bulkimagecreator.service import GeminiImageGenerationService

    mock_candidate = MagicMock()
    mock_candidate.content.parts = []
    mock_candidate.finish_reason = "SAFETY"
    mock_candidate.finish_message = "Content violates safety policies"
    mock_response = MagicMock()
    mock_response.prompt_feedback = None
    mock_response.candidates = [mock_candidate]

    mock_client = MagicMock()
    mock_client.models.generate_content.return_value = mock_response

    service = GeminiImageGenerationService(client=mock_client)
    ref = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref, format="PNG")

    with pytest.raises(SafetyBlockError, match="Content violates safety policies"):
        service.generate_image(prompt="Prompt", reference_images=[ref])


def test_gemini_service_maps_prompt_feedback_block_to_safety_block_error(tmp_path: Path) -> None:
    from unittest.mock import MagicMock
    import pytest
    from bulkimagecreator.exceptions import SafetyBlockError
    from bulkimagecreator.service import GeminiImageGenerationService

    mock_feedback = MagicMock()
    mock_feedback.block_reason = "SAFETY"
    mock_feedback.block_reason_message = "Prompt contains blocked terms"
    mock_response = MagicMock()
    mock_response.prompt_feedback = mock_feedback
    mock_response.candidates = []

    mock_client = MagicMock()
    mock_client.models.generate_content.return_value = mock_response

    service = GeminiImageGenerationService(client=mock_client)
    ref = tmp_path / "ref.png"
    Image.new("RGB", (32, 32), color="red").save(ref, format="PNG")

    with pytest.raises(SafetyBlockError, match="Prompt contains blocked terms"):
        service.generate_image(prompt="Prompt", reference_images=[ref])


